### ISSUE TITLE
Failed to open stream on Unity2018.3.1f1

### ISSUE THREAD

**Issue by WoW55QQ** [keijiro/DepthkitTest#1]
I run scene named 'Test' that throws a exception:
Failed to open stream (H:/UnityProject/DepthkitTest/Assets/StreamingAssets\Julianne.mov).
UnityEngine.Debug:LogError(Object)
Klak.Hap.HapPlayer:OpenInternal() (at Library/PackageCache/jp.keijiro.klak.hap@4a58abc8995a1c6fc5300e7552df68543da8977b/Runtime/HapPlayer.cs:118)
Klak.Hap.HapPlayer:Open(String, PathMode) (at Library/PackageCache/jp.keijiro.klak.hap@4a58abc8995a1c6fc5300e7552df68543da8977b/Runtime/HapPlayer.cs:94)
CustomRenderer:Start() (at Assets/CustomRenderer.cs:37)
Is there any solution? Thx

**Comment by keijiro** [comment]
The example clip files (*.mov) from the Depthkit Unity plugin have to be transcoded into HAP and put in the StreamingAssets directory.

**Comment by keijiro** [comment]
I'm closing the issue. Please feel free to reopen for further questions.
