### ISSUE TITLE
Convert Metadata for depthkit? 

### ISSUE THREAD

**Issue by skymeson** [keijiro/DepthkitTest#3]
I'd like to use this with my own depthkit video files. If I change the video file to a different one nothing shows up. Do I need to create a metadata file? I see there are some editor scripts that do that but I'm not sure how to use them. The menu option is always grayed out for me. Thank you!

**Comment by keijiro** [comment]
Import a metadata json file (with `.txt` extension) exported from Depthkit, then right-click it in the Project view and select Depthkit -> Convert Metadata.

**Comment by skymeson** [comment]
Thanks! 

I figured out my other issue too based on someone else's question. I had an issue using my own video file but then I realized it needed to be converted to HAP format. If its not encoded correctly, no video will be processed. Just in case someone else has a similar problem.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
